features/urls.py
from django.urls import path
from django.contrib import admin

from features import views

home/urls.py
from django.contrib import admin
from django.urls import path,include
import features
from . import views
app_name='home'
urlpatterns = [
    path('',views.home,name="hom" ),
    path('logout/',views.logout ),
    path('search/',features.views.search),
    path('search/trains',features.views.getTrains),
    path('schedule/',features.views.schedule),
    path('schedule/trains',features.views.getTinfo),
    path('addR/',features.views.addR,name="addR"),
    path('addST/',features.views.addST),
    path('addT/',features.views.addT),
    path('addRT/',features.views.addRT),
    path('search/search/trains/cva/', features.views.cva),
    path('search/book1/', features.views.book1),
    path('search/book1/book/', features.views.book),
    path('cancel/',features.views.cancel),
    path('cancel/cancel/cn/',features.views.cn),
    path('pnr/',features.views.pnr,name="pnr"),
    ]

rail/urls.py
from django.contrib import admin
from django.urls import path,include
from features import views
from home import views
app_name='basic'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.log,name='log'),
    path('register/',views.Reg,name="reg"),
    path('logout/',views.logout,name="logout"),
    path('home/',include('home.urls',namespace="home"),name="home"),

]

features/models.py
from django.db import models

# Create your models here.
class Members(models.Model):
    username=models.CharField(max_length=250)
    password=models.CharField(max_length=16)
    email=models.CharField(max_length=250)
    number=models.CharField(max_length=10)

    def __str__(self):
        return self.username

home/models.py
from django.db import models

# Create your models here.
class Trains(models.Model):
    tno=models.CharField(primary_key=True,max_length=50)
    tname=models.CharField(max_length=50)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)

    def __str__(self):
        return self.tno

class Route(models.Model):
    rid=models.CharField(max_length=50)
    ostation=models.CharField(max_length=50)
    dstation=models.CharField(max_length=50)
    def __str__(self):
        return self.rid

class Station(models.Model):
    sid=models.CharField(primary_key=True,max_length=50)
    sname=models.CharField(max_length=50)
    def __str__(self):
        return self.sid


class RouteStation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    sid=models.ForeignKey('Station',on_delete=models.CASCADE)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)
    order=models.IntegerField()
    atime=models.CharField(max_length=50)

class Reservation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    user=models.CharField(max_length=50)
    nos=models.IntegerField()
    date=models.CharField(max_length=50)
    amt=models.IntegerField()
    cls=models.CharField(max_length=50)
    status=models.CharField(max_length=50)
    pnr=models.CharField(max_length=50)
    src=models.CharField(max_length=50)
    des=models.CharField(max_length=50)




class Payment(models.Model):
    pnr=models.CharField(max_length=50)
    user=models.CharField(max_length=50)
    amt=models.IntegerField()
    mtd=models.CharField(max_length=50)
    date=models.CharField(max_length=50)
    cancel=models.CharField(max_length=50)

features/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class Usearch(forms.Form):
    src=forms.CharField(max_length=50)
    des = forms.CharField(max_length=50)

class Trsc (forms.Form):
    tnum=forms.IntegerField()

class AddR(forms.Form):
    rid=forms.CharField(max_length=50)
    ostation=forms.CharField(max_length=50)
    dstation=forms.CharField(max_length=50)

class AddST(forms.Form):
    sid=forms.CharField(max_length=50)
    sname=forms.CharField(max_length=50)

class AddT(forms.Form):
    rid=forms.CharField(max_length=50)
    tno=forms.CharField(max_length=50)
    tname=forms.CharField(max_length=50)

class AddRT(forms.Form):
    tno=forms.CharField(max_length=50)
    sid= forms.CharField(max_length=50)
    rid=forms.CharField(max_length=50)
    order=forms.IntegerField()
    atime=forms.CharField(max_length=50)

class Pnr(forms.Form):
    pnr=forms.CharField(max_length=50)

class Book(forms.Form):
    cls=forms.CharField(max_length=10)
    dt=forms.CharField(max_length=10)

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserLogin(forms.Form):
    username = forms.CharField(max_length=250)
    password = forms.CharField(max_length=16, widget=forms.PasswordInput())


class UserReg(forms.ModelForm):
    number=forms.CharField(required=True)
    class Meta:
        model=User
        fields=['username','password','email','number']

    def save(self, commit=True):
        user = super(UserReg, self).save(commit=False)
        user.number = self.cleaned_data["number"]
        if commit:
            user.save()
        return user

features/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.db.models import Max
from django.template import loader
from .models import Members
from .forms import Trsc,Usearch,AddR,AddST,AddT,AddRT
import json

from home.models import RouteStation,Station,Route,Trains,Reservation,Payment
def getTrains(request):
    if request.method=='POST':
        form=Usearch(request.POST)
        if form.is_valid():

            data=form.cleaned_data
            src=data['src']
            des=data['des']
            a=RouteStation.objects.filter(sid=des)
            x=[]
            o=0
            for i in a:
                tno=i.tno
                b=RouteStation.objects.filter(tno=tno,sid=src)
                for j in b:
                    if j.order<i.order:
                        x.append(j)
                        o=i.order-j.order

        else:
            return HttpResponse('<h1>invalid Data</h1>')
        return render(request,'features/trains.html',{'data':x,'o':o,'src':src,'des':des})
    return HttpResponse('<h1>Wrong REq</h1>')




def schedule(request):
    a=Trains.objects.all()
    return render(request,'features/schedule.html',{'a':a})

def getTinfo(request):
    form=Trsc(request.GET)
    if form.is_valid():
        data=form.cleaned_data
        tno=data['tnum']
        a=RouteStation.objects.filter(tno=tno).order_by('order')


        return render(request,'features/trinfo.html',{'data':a})

    return HttpResponse('<h1>DAta invalid<h1>')







def search(request):
    a=Station.objects.all()
    return render(request,'features/seat.html',{'a':a})

def addR(request):
    if request.method == 'POST':
        form = AddR(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            a=Route()
            a.rid=data['rid']
            a.ostation=data['ostation']
            a.dstation=data['dstation']
            a.save()
            return redirect('/home/addR')
        else:
            return HttpResponse('<h1>Invalid Data</h1>')






    a=Station.objects.all()

    return render(request,'features/addR.html',{'stn':a})


def addST(request):
    if request.method == 'POST':
        form = AddST(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            a = Station()
            a.sid = data['sid']
            a.sname = data['sname']
            a.save()
            return redirect('/home/addST')
        else:
            return HttpResponse('<h1>Invalid Data</h1>')

    return render(request, 'features/addST.html')

def addT(request):
    if request.method == 'POST':
        form = AddT(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            a=Trains()
            a.tno=data['tno']
            a.tname=data['tname']
            r1=Route.objects.get(rid=data['rid'])
            a.rid=r1
            a.save()
            return redirect('/home/addT')
        else:
            return HttpResponse('<h1>Invalid Data</h1>')






    a=Route.objects.all()

    return render(request,'features/addT.html',{'tr':a})

def addRT(request):
    if request.method == 'POST':
        form = AddRT(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            a = RouteStation()
            t1= Trains.objects.get(tno=data['tno'])
            a.tno = t1
            s1=Station.objects.get(sid=data['sid'])
            a.sid = s1
            r1=Route.objects.get(rid=data['rid'])
            a.rid = r1
            a.order=data['order']
            a.atime=data['atime']
            a.save()
            return redirect('/home/addRT')
        else:
            return HttpResponse(form.errors)

    a = Route.objects.all()
    b=Trains.objects.all()
    c=Station.objects.all
    return render(request, 'features/addRT.html', {'rt': a,'tr':b,'st':c})


def cva(request):
    if request.method=='POST':
        tn1=request.POST['tno']
        o=int(request.POST['od'])

        cls=request.POST['cls']
        p=0
        if cls=='AC':
            p=120*o
        if cls=='SL':
            p=80*o
        if cls=='3A':
            p=100*o
        if cls=='2S':
            p=50*o
        dt=request.POST['dt']
        c=0
        a=Reservation.objects.filter(tno=tn1,cls=cls,date=dt)

        for i in a:
            c=c+i.nos
        if c>30:
            x="Waiting-"+str(c-30)
            data = json.dumps({
                'read': x,
                'price': p,
            })
            return HttpResponse(data,content_type='application/json')
        else:
            x="Available-"+str(30-c)
            data = json.dumps({
                'read': x,
                'price': p,
            })
            return HttpResponse(data,content_type='application/json')

def book1(request):
    if(request.method=='POST'):
        dt=request.POST['date']
        src=request.POST['src']
        des=request.POST['des']
        tno=request.POST['bk']
        cls = request.POST['cls'+str(tno)]
        nos=request.POST['nos'+str(tno)]
        pr=request.POST['price'+str(tno)]
        tname=Trains.objects.get(tno=tno).tname
        return render(request,'features/payment.html',{'price':int(pr)*int(nos),'dt':dt,'cls':cls,'tno':tno,'nos':nos,'tname':tname,'src':src,'des':des})


def book(request):

    if request.method=='POST':
        nos=int(request.POST['nos'])
        tno=request.POST['tno']
        dt=request.POST['date']
        tn1=Trains.objects.get(tno=tno)
        cls=request.POST['cls']
        op=request.POST['select']
        tname=request.POST['tname']
        src=request.POST['src']
        des=request.POST['des']
        price=int(request.POST['price'])
        pp=price/nos
        mtd='Paytm'
        if op=='option1':
            crd=request.POST['crd']
            nam=request.POST['nam']
            cvv=request.POST['cvv']
            exp=request.POST['exp']
            mtd='Credit/Debit Card'
            if len(crd)!=16 or len(cvv)!=3:
                return render(request,'features/nopay.html')


        c = 0
        f=0
        pay=Payment()
        pay.user=request.user
        pay.amt=price
        pay.date=dt
        pay.mtd=mtd
        pay.cancel='NO'

        a = Reservation.objects.filter(tno=tno, cls=cls, date=dt)
        c1=Reservation.objects.all()
        cp=0
        for i in c1:
            cp=max(cp,int(i.pnr))
        for i in a:
            c = c + i.nos
        if c<30:
            if nos>(30-c):
                b=Reservation()
                b.cls=cls
                b.tno=tn1
                b.status="C"
                b.nos=30-c
                b.amt=200
                b.date=dt
                b.user=request.user
                b.pnr=cp+1
                b.src=src
                b.des=des
                b.save()
                e = Reservation()
                e.cls = cls
                e.tno = tn1
                e.status = "W"
                e.nos = nos-(30 - c)
                e.amt = price
                e.date = dt
                e.user = request.user
                e.pnr = cp + 1
                e.src=src
                e.des=des
                e.save()
                f=1
            else:
                b = Reservation()
                b.cls = cls
                b.tno = tn1
                b.status = "C"
                b.nos = nos
                b.amt = price
                b.date = dt
                b.user = request.user
                b.pnr = cp + 1
                b.src=src
                b.des=des
                b.save()
                f = 1
        else:
            b = Reservation()
            b.cls = cls
            b.tno = tn1
            b.status = "W"
            b.nos = nos
            b.amt = price
            b.date = dt
            b.user = request.user
            b.pnr = cp + 1
            b.save()
            f=2
        c=0
        a = Reservation.objects.filter(tno=tno, cls=cls, date=dt)
        for i in a:
            c = c + i.nos

        pay.pnr = cp+1
        pay.save()
        return render(request,"features/final.html",{'tname':tname,'tno':tno,'date':dt,'src':src,'des':des,'cls':cls,'pnr':(cp+1),'nos':nos,'dt':dt})



def cancel(request):
    a=Reservation.objects.filter(user=request.user).values('pnr','date','tno','src','des','cls','nos').distinct()
    return render(request,'features/cancel.html',{'res':a})

def cn(request):

    if request.method=='POST':


        pnr=request.POST['id']
        a=Reservation.objects.filter(pnr=pnr)
        z=Payment.objects.filter(pnr=pnr,cancel='NO')
        for j in z:
            amt = j.amt
            j.cancel='YES'
            j.save()

        c=0
        cls='X'

        for i in a:
            if i.status=='C':
                c=c+i.nos
            cls=i.cls
        a.delete()
        a=Reservation.objects.all()
        f=0
        for i in a:
            if i.status=='W' and i.cls==cls:
                if i.nos<=c:
                    c=c-i.nos
                    i.status='C'
                    i.save()
                else:
                    f=1
                    b=Reservation()
                    b.cls = i.cls
                    b.tno = i.tno
                    b.status = "C"
                    b.nos = c
                    b.amt = 200
                    b.date = i.date
                    b.user = i.user
                    b.pnr = i.pnr
                    b.save()
                    i.nos=i.nos-c
                    i.save()
                    c=0
                    break
        return HttpResponse(amt)

def pnr(request):
    if request.method=='POST':
        pnr=request.POST['pnr']
        a=Reservation.objects.filter(pnr=pnr)

        return render(request,'features/pnr.html',{'r':a})


    return render(request,'features/pnr.html')

home/views.py
from django.shortcuts import render
from django.template import loader
from features.models import Members
from .forms import UserLogin,UserReg
from django.contrib import auth
from django.contrib.auth import authenticate,login
from django.shortcuts import render,redirect
from django.http import HttpResponse
# Create your views here.
def home(request):
    return render(request,'features/home.html')

def logout(request):
    auth.logout(request)
    return redirect("http://127.0.0.1:8500/")


def log(request):
    template = loader.get_template('features/login.html')
    if request.method=='POST':
        form=UserLogin(request.POST)
        if form.is_valid():

            data=form.cleaned_data
            username=data['username']
            password=data['password']
            user=authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('home/',request)

            return HttpResponse('<h1>Invalid Credentials</h1>')
        return HttpResponse('<h1>invalid Data</h1>')
    else:
        return HttpResponse(template.render({}, request))

def Reg(request):
    template = loader.get_template('features/Register.html')
    if request.method=='POST':
        form=UserReg(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            data=form.cleaned_data
            usr=data['username']
            pas=data['password']
            eml=data['email']
            nmb=data['number']
            a=Members()
            a.username=usr
            a.password=pas
            a.email=eml
            a.number=nmb
            a.save()
            user.set_password(pas)

            user.save()
            user=authenticate(username=usr,password=pas)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return render(request,'features/home.html')

            return HttpResponse('<h1>VALID</h1>')
        return HttpResponse(template.render({'form':form},request))
    else:
        return HttpResponse(template.render({},request))

features/templates/features/Register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Railway System</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}

    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <style>
        body
        {
            background-image:url('{%static "images/mrt.jpg" %}');
            background-size:100%;
            background-repeat:no-repeat;


        }
        .rform
        {
            padding:20px 50px;;
            background-color:rgba(0, 51, 204);
            width:30%;
            height:400px;
            margin-top:100px;
            margin-left:95px;
            border-radius:30px;
            opacity: 70%;
            }
            .white
            {
            color:white;
            }
        </style>
</head>
<center><body>
    <h1 style="text-align:center;font-family:sans-seriff;">Register</h1>
    {%if form.errors%}

    <h3>{{form.errors}}</h3>

    {%else%}
    <form class="rform" action="" method="POST">
        {% csrf_token %}
        <span class="white">Username:</span><br/><input type="text" name="username"><br/><br/>
        <span class="white">Password:</span><br/><input type="password" name="password"><br/><br/>

        <span class="white">Email:</span><br/><input type="email" name="email"><br/><br/>
        <span class="white">Phone Number:</span><br/><input type="text" name="number"><br/><br/>
        <input class="btn btn-success" type="submit" value="Register"><br/>
    </form>
    {%endif%}
</body>
</html>

features/templates/features/addR.html
{% extends 'features/srbase.html'%}
{% block body%}
<h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:yellow;">Add Routes</span></h2>


<center><form action="" method="post">
    {%csrf_token%}
    <span style="color:yellow;">Route ID:</span><input type="text" name="rid">
    <span style="color:yellow;">Origin Station:</span><select name="ostation">
        {%for i in stn%}
        <option value="{{i.sid}}">{{i.sname}}</option>
        {%endfor%}
    </select>
    <span style="color:yellow;">Destination Station:</span><select name="dstation">
        {%for i in stn%}
        <option value="{{i.sid}}">{{i.sname}}</option>
        {%endfor%}
    </select>
    <input type="submit" class="btn btn-success">
</form></center>
{%endblock%}

features/templates/features/addRT.html
{% extends 'features/srbase.html'%}
{% block body%}
<h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:yellow;">Add Route Station</span></h2>


<center><form action="" method="post">
    {%csrf_token%}
    <span style="color:yellow;">Select Train:</span><select name="tno">
        {%for i in tr%}
        <option value="{{i.tno}}">{{i.tname}}</option>
        {%endfor%}
    </select>
    <span style="color:yellow;">Station Id:</span><select name="sid">
        {%for i in st%}
        <option value="{{i.sid}}">{{i.sname}}</option>
        {%endfor%}
    </select>
    <span style="color:yellow;">Route ID:</span><select name="rid">
        {%for i in rt%}
        <option value="{{i.rid}}">{{i.ostation}}-{{i.dstation}}</option>
        {%endfor%}
    </select>
    <span style="color:yellow;">Station no:</span><input type="number" name="order">
        <span style="color:yellow;">Arrival Time:</span><input type="text" name="atime">


    <input type="submit" class="btn btn-success">
</form></center>
{%endblock%}

features/templates/features/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Railway System</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}
    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">


    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <style>
        body{
            background-image:url('{% static "images/hompage.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;
        }
        .sty
        {
            font-family: 'Dancing Script', cursive;
            color:white;
        }
        .row1{




            background-color:rgba(0,0,0,0.6);


        }
    </style>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

features/templates/features/cancel.html
{% extends 'features/srbase.html' %}
{%block body%}
    <h1 style="text-align:center;font-family:sans-seriff; color: yellow;">Current Reservations</h1>

        {%csrf_token%}
    <div class="container">
    {% for i in res %}
        <div class="tick" style="font-size:13px;color:white;padding:18px;padding-left:40px;">

            &nbsp&nbspDate       :{{i.date}}<br/>
            &nbsp&nbspTrain no   :{{i.tno}}<br/>
            &nbsp&nbspPNR        :{{i.pnr}}<br/>
            &nbsp&nbspSrc        :{{i.src}}<br/>
            &nbsp&nbspDes        :{{i.des}}<br/>
                            <button class="btn btn-danger" value="{{i.pnr}}" style="float:right;border-radius:50%;" onclick="y(this.value)"type="submit">Cancel</button><br/>

        </div>
            <br/><br/>
        {%endfor%}

</div>

     <script>
     function y(vl)
    {



        $.ajax({
            type:'POST',
            url:'cancel/cn/',
            data:{
                    id:vl,
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()

                  },
        success:function(data){

            alert("Cancelled Tickets||Amount Refunded:"+data);
            window.location.href=window.location.href;
                               }
            }
                )

    }
    </script>
{%endblock%}

features/templates/features/final.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket Details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .det
        {
            background-color:rgba(0,0,0,0.7);
            color:white;
            }

         body
         {
         background-image:url('{% static "images/comp.jpg"%}');
         background-size:100% 100%;
         height:650px;
         background-repeat:no-repeat;
         }

    </style>
</head>
<body>
<h1 style="text-align:center;font-family:sans-seriff;">Tickets Booked</h1>
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 det">
    <h3>Ticket Details</h3>
    Train Name   :<b>{{tname}}</b><br/>
    Train No     :<b>{{tno}}</b><br/>
    PNR          :<b>{{pnr}}</b><br/>
    No of seats  :<b>{{nos}}</b><br/>
    Booking Class:<b>{{cls}}</b><br/>
    Booking Date :<b>{{dt}}</b><br/>

    <h4>For Further Enquiry Check PNR</h4>
    <a href="{%url 'home:hom'%}"><button class="btn btn-success">Back To Homepage</button></a>
    <a href="{%url 'home:pnr'%}"><button class="btn btn-info">Check PNR</button></a>
    </div>

    </div>
    </div>

</body>
</html>

features/templates/features/home.html
{% extends 'features/base.html' %}

{% block body %}
    <div class="container-fluid">
        <div class="row1 row">
            <div class="col-lg-4">
                <span class="sty" style="font-size:40px; color: yellow;">Railway Reservation System</span>
            </div>
            <div class="col-lg-6"></div>
            <div class="col-lg-1"><span class="sty" style="font-size:17px;">Welcome:{{request.user}}</span></div>
            <div class="col-lg-1"><a href="logout"><button class="btn btn-danger">Log Out</button> </a></div>
        </div>
        <div class="row" style="margin-top:0px; opacity: 80%; background-color: blue;">
            <div class="col-lg-1"></div>
            {% if request.user.is_superuser %}
            <a href="addT"><button class="btn btn-basic">Add Trains</button></a>
            <a href="addST"><button class="btn btn-primary">Add Stations</button></a>
            <a href="addR"><button class="btn btn-warning">Add Route</button></a>
            <a href="addRT"><button class="btn btn-default">Add Route Station</button></a>

            {% endif %}
             <a href="search"><button class="btn btn-success">Search/Book Trains</button></a>
             <a href="schedule"><button class="btn btn-info">Check Schedule</button></a>
             <a href="pnr"><button class="btn btn-warning">Check PNR</button></a>
             <a href="cancel"><button class="btn btn-danger">Cancel Seat</button></a>

            <div class="col-lg-1"></div>
        </div>
    </div>

{% endblock %}

features/templates/features/nopay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Tickets Cannot be Booked
    Payment Failed
</body>
</html>

features/templates/features/pnr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PNR NUMBER</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}

    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <style>
        body{
            background-image:url('{% static "images/number.jpg"%}');
            background-size:100%;
            background-repeat:no-repeat;


        }
        .sty
        {
            font-family: 'Arial';
            color:white;
        }
        .hd
        {
            margin-left:400px;

            }
         .tform{
            background-color:rgba(0,0,0,0.3);
            }
            .fpnr
            {
                width:20%;
                margin-left:500px;
                margin-top:150px;
                padding:15px;
                background-color:rgba(0,0,0,0.3);
                }

        .tick{
            width:20%;
            height:150px;
           background-image:url('{% static "images/ticket6"%}');
            background-size:100% 100%;
            background-repeat:no-repeat;
            }
    </style>
</head>
<body>

{%if r%}
<h2 style="text-align:center"> Current PNR Status</h2>
<div class="fpnr">
{%for i in r%}

    <h4 class="sty">PNR-{{i.pnr}}<br/>
    NO of seats-{{i.nos}}<br/>
    Status-{{i.status}}<br/><br/></h4>

{%endfor%}
        <a href="{%url 'home:hom'%}"><button class="btn btn-success">Back To Homepage</button></a>

</div>
{%else%}
<h1 style="text-align:center;font-family:sans seriff; color: yellow; background-color: green; opacity: 70%; ">ENTER PNR NUMBER</h1>

<form class="fpnr" action="" method="POST" style="background-color: green; opacity: 70%;">
    {%csrf_token%}
    <span class="sty">PASSENGER NAME RECORD: </span><input type="text" name="pnr" required=""><br/><br/>
    <center><input type="submit" class="btn btn-primary" value="Check"></center>
</form>
{%endif%}

features/templates/features/seat.html
{% extends 'features/srbase.html' %}

{% block body %}
    <h2 style="text-align:center;"><span class="sty" style="font-size:50px;color:yellow;">Search Trains </span></h2>
    <br/><br/>
    
    <center><form class="form-inline" style="margin-left:200px;"action="trains" method="POST">
        {% csrf_token %}
        <span class="sty" style="font-size:30px;color:yellow;">From:</span><select name="src">
            {% for i in a %}
            <option value="{{i.sid}}">{{i.sname}}</option>
            {%endfor%}
        </select>
        <span class="sty" style="font-size:30px;color:yellow;">Destination:</span>
        <select name="des">
            {% for i in a %}
            <option value="{{i.sid}}">{{i.sname}}</option>
            {%endfor%}
        </select>
        &nbsp
        <input class="btn btn-primary" type="submit" value="Search">
    </form></center>
{% endblock%}